const animeList = [
    {
        title: "Dragon Ball Z",
        id: "dragon-ball-z",
        image: require('../images/thumbnails/dbz.jpg'),
        videosrc: require('../videos/dbz/dbz1.mp4'),
        description: "Dragon Ball Z is a Japanese manga series written and illustrated by Akira Toriyama. It is the sequel to the Dragon Ball manga series. The series began as a serialized manga in the late 1990s, and was published as a manga series in North America by Shueisha in 1995. The series was later serialized as a TV series in the United States and Canada in 1996, and was re-mastered for the North American release in 1997. The series was also serialized in Japan as Dragon Ball Z: The First Arc in 1998, and was re-mastered for the Japanese release in 1999. The series was re-mastered for the European release in 2000, and was re-mastered for the Korean release in 2001. The series was re-mastered for the Taiwanese release in 2002, and was re-mastered for the Hong Kong release in 2003. The series was re-mastered for the German release in 2004, and was re-mastered for the French release in 2005. The series was re-mastered for the Italian release in 2006, and was re-mastered for the Spanish release in 2007. The series was re-mastered for the Russian release in 2008, and was re-mastered for the Dutch release in 2009. The series was re-mastered for the Swedish release in 2010, and was re-mastered for the Turkish release in 2011. The series was re-mastered for the Polish release in 2012, and was re-mastered for the Czech release in 2013. The series was re-mastered for the Danish release in 2014, and was re-mastered for the Norwegian release in 2015. The series was re-mastered for the Greek release in 2016, and was re-mastered for the Turkish release in 2017. The series was re-mastered for the Korean release in 2018, and was re-mastered for the Chinese release in 2019. The series was re-mastered for the Japanese release in 2020."
    },
    {
        title: "Naruto",
        id: "naruto",
        image: require('../images/thumbnails/naruto.jpg'),
        videosrc: require('../videos/naruto/naruto.mp4'),
        description: "Naruto is a Japanese manga series written and illustrated by Masashi Kishimoto. It is the tenth volume of the series, and the first in the series to be published in North America. The series was serialized in the United States and Canada in 2002, and was re-mastered for the Japanese release in 2003. The series was re-mastered for the European release in 2004, and was re-mastered for the Hong Kong release in 2005. The series was re-mastered for the German release in 2006, and was re-mastered for the French release in 2007. The series was re-mastered for the Italian release in 2008, and was re-mastered for the Spanish release in 2009. The series was re-mastered for the Russian release in 2010, and was re-mastered for the Dutch release in 2011. The series was re-mastered for the Swedish release in 2012, and was re-mastered for the Turkish release in 2013. The series was re-mastered for the Polish release in 2014, and was re-mastered for the Czech release in 2015. The series was re-mastered for the Danish release in 2016, and was re-mastered for the Norwegian release in 2017. The series was re-mastered for the Greek release in 2018, and was re-mastered for the Turkish release in 2019. The series was re-mastered for the Korean release in 2020."
    }
]

export default animeList;